version: '3.8'

services:
  # Backend Services
  api-gateway:
    build: ./lms_micro_services/api-gateway
    container_name: lms-api-gateway
    ports:
      - "8000:8000"
    environment:
      - AUTH_SERVICE_URL=http://auth-service:8001
      - CONTENT_SERVICE_URL=http://content-service:8002
      - ASSIGNMENT_SERVICE_URL=http://assignment-service:8004
    networks:
      - lms-network
    depends_on:
      - auth-service
      - content-service
      - assignment-service
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    restart: unless-stopped

  auth-service:
    build: ./lms_micro_services/auth-service
    container_name: lms-auth-service
    environment:
      # Sử dụng kết nối database hiện có
      - DATABASE_URL=postgresql://admin:Mypassword123@14.161.50.86:25432/postgres
      - ENVIRONMENT=development
      - DEPLOYMENT_TYPE=single-server
      - SECRET_KEY=your_secret_key
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
    networks:
      - lms-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    restart: unless-stopped

  content-service:
    build: ./lms_micro_services/content-service
    container_name: lms-content-service
    environment:
      # Sử dụng kết nối MongoDB hiện có
      - MONGODB_URL=mongodb://admin:Mypassword123@14.161.50.86:27017/content_db?authSource=admin
      - MONGODB_DB_NAME=content_db
      - ENVIRONMENT=development
      - SERVICE_NAME=content-service
      - HOST=0.0.0.0
      - PORT=8002
      - DEBUG=true
      - AUTH_SERVICE_URL=http://auth-service:8001
      - JWT_SECRET_KEY=microservices-lms-secret-key-2025-production-secure-auth-service
      - JWT_ALGORITHM=HS256
    networks:
      - lms-network
    depends_on:
      - auth-service
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8002/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    restart: unless-stopped

  assignment-service:
    build: ./lms_micro_services/assignment-service
    container_name: lms-assignment-service
    environment:
      # Sử dụng kết nối database hiện có
      - DATABASE_URL=postgresql+asyncpg://admin:Mypassword123@14.161.50.86:25432/postgres
      - POSTGRES_HOST=14.161.50.86
      - POSTGRES_PORT=25432
      - POSTGRES_DB=postgres
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=Mypassword123
      - AUTH_SERVICE_URL=http://auth-service:8001
      - CONTENT_SERVICE_URL=http://content-service:8002
      - JWT_SECRET_KEY=your-jwt-secret-key-here-change-in-production
    networks:
      - lms-network
    depends_on:
      - auth-service
      - content-service
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8004/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    restart: unless-stopped

  # Frontend Applications
  frontend-admin:
    build: ./lms_micro_services/frontend-admin
    container_name: lms-frontend-admin
    ports:
      - "3001:80"
    environment:
      - REACT_APP_API_BASE_URL=http://localhost:8000
    # Thêm giới hạn tài nguyên để tránh lỗi OOM
    mem_limit: 4g
    mem_reservation: 2g
    networks:
      - lms-network
    depends_on:
      - api-gateway
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    restart: unless-stopped

  frontend-teacher:
    build: ./lms_micro_services/frontend-teacher
    container_name: lms-frontend-teacher
    ports:
      - "3002:80"
    environment:
      - REACT_APP_API_BASE_URL=http://localhost:8000
    # Thêm giới hạn tài nguyên để tránh lỗi OOM
    mem_limit: 4g
    mem_reservation: 2g
    networks:
      - lms-network
    depends_on:
      - api-gateway
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    restart: unless-stopped

  frontend-student:
    build: ./lms_micro_services/frontend-student
    container_name: lms-frontend-student
    ports:
      - "3003:80"
    environment:
      - REACT_APP_API_BASE_URL=http://localhost:8000
    # Thêm giới hạn tài nguyên để tránh lỗi OOM
    mem_limit: 4g
    mem_reservation: 2g
    networks:
      - lms-network
    depends_on:
      - api-gateway
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    restart: unless-stopped

networks:
  lms-network:
    driver: bridge